"""GitHub Launch Mode — create a real repo + README + milestones + issues from the plan.

Two halves, deliberately separated:
  • `build_launch_plan(...)` — pure, deterministic, no network: slugs a repo name, writes a
    README, and turns the ExecutionPlan's sprints/backlog into milestones + issues.
  • `launch_github(plan, token=...)` — the REAL side: live GitHub REST API calls via
    `infra.http` (retry + rate-limit). With **no token** it returns a labeled preview and
    makes **zero** network calls, so a demo never creates a repo by accident; with a PAT it
    genuinely creates everything and returns the live URLs.

Needs a `repo`-scoped PAT (`APS_GITHUB_PAT`). Verify live with
`python scripts/live_github_launch_smoke.py`.
"""
from __future__ import annotations

import base64
import os
import re

from pydantic import BaseModel, Field

from aps.state.models import PRD, ExecutionPlan, PitchPackage

_GH = "https://api.github.com"
_MAX_ISSUES = 30


def _slug(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")
    return (s[:80] or "startup-mvp")


class LaunchIssue(BaseModel):
    title: str
    body: str
    labels: list[str] = Field(default_factory=list)
    sprint: int | None = None


class LaunchPlan(BaseModel):
    idea: str
    repo_name: str
    description: str
    readme: str
    milestones: list[str] = Field(default_factory=list)
    issues: list[LaunchIssue] = Field(default_factory=list)
    # Full repo scaffold as (path, content) pairs — committed together as the first commit.
    # Always includes README.md; richer when APS_LAUNCH_SCAFFOLD is on (the default).
    files: list[tuple[str, str]] = Field(default_factory=list)


class LaunchResult(BaseModel):
    created: bool
    dry_run: bool
    repo_url: str | None = None
    full_name: str | None = None
    issue_urls: list[str] = Field(default_factory=list)
    milestones_created: int = 0
    files_created: int = 0
    message: str = ""


def _readme(idea: str, prd: PRD | None, pitch: PitchPackage | None) -> str:
    lines = [f"# {idea}\n", "> Generated by **Autonomous Product Studio** — idea → execution package.\n"]
    if prd and prd.mvp_scope:
        lines += ["\n## MVP Scope\n", prd.mvp_scope + "\n"]
    if prd and prd.features:
        lines += ["\n## Features\n"] + [f"- **{f.title}** `[{f.priority}]` — {f.description}"
                                        for f in prd.features]
    if pitch and pitch.pitch_outline:
        lines += ["\n## Pitch\n", pitch.pitch_outline + "\n"]
    return "\n".join(lines) + "\n"


def build_launch_plan(idea: str, prd: PRD | None, execution: ExecutionPlan | None,
                      pitch: PitchPackage | None = None, trd=None) -> LaunchPlan:
    # Full repo scaffold (README + models/routes/docs/Docker/CI) from the already-generated
    # artifacts — pure, no API. APS_LAUNCH_SCAFFOLD=false → README-only (legacy behavior).
    if os.getenv("APS_LAUNCH_SCAFFOLD", "true").lower() != "false":
        try:
            from aps.launch.scaffold import build_scaffold
            files = build_scaffold(idea, prd, trd, execution, pitch)
        except Exception:
            files = [("README.md", _readme(idea, prd, pitch))]
    else:
        files = [("README.md", _readme(idea, prd, pitch))]
    # the README in the scaffold (first entry) is the canonical one for the plan
    readme = next((c for p, c in files if p == "README.md"), _readme(idea, prd, pitch))

    # map each backlog item to its sprint number (if any)
    item_sprint: dict[str, int] = {}
    sprints = execution.sprints if execution else []
    for s in sprints:
        for it in s.get("items", []):
            key = it.get("id") or it.get("title", "")
            if key:
                item_sprint[key] = s.get("sprint")

    issues: list[LaunchIssue] = []
    for it in (execution.backlog if execution else [])[:_MAX_ISSUES]:
        key = it.get("id") or it.get("title", "")
        labels = [v for v in (it.get("type"), it.get("priority")) if v]
        body = (f"**Type:** {it.get('type', 'task')}  \n"
                f"**Priority:** {it.get('priority', '—')}  \n"
                f"**Estimate:** {it.get('points', '—')} pts\n\n"
                f"_Auto-generated from the APS execution plan._")
        issues.append(LaunchIssue(title=it.get("title", "Untitled"), body=body,
                                  labels=labels, sprint=item_sprint.get(key)))

    return LaunchPlan(
        idea=idea,
        repo_name=_slug(idea),
        description=(idea or "")[:200],
        readme=readme,
        milestones=[f"Sprint {s.get('sprint')}" for s in sprints],
        issues=issues,
        files=files,
    )


def launch_github(plan: LaunchPlan, *, token: str | None = None, owner: str | None = None,
                  private: bool = False, dry_run: bool = False) -> LaunchResult:
    """Create the repo for real (with a PAT) or return a preview (without one).

    Multi-tenant rule: the repo is created in the account that owns the supplied `token`, so
    each user must bring their OWN GitHub PAT (sent per-request). The server-wide
    `APS_GITHUB_PAT` is used as a fallback ONLY when `APS_GITHUB_ALLOW_SHARED_PAT=true`
    (single-operator / local demo). In a deployed multi-user build that flag stays off, so a
    request without a user token yields a safe preview instead of a repo in the operator's
    account.
    """
    if not token and os.getenv("APS_GITHUB_ALLOW_SHARED_PAT", "false").lower() == "true":
        token = os.getenv("APS_GITHUB_PAT")
    if dry_run or not token:
        return LaunchResult(
            created=False, dry_run=True, files_created=len(plan.files),
            full_name=f"{owner or '<your-account>'}/{plan.repo_name}",
            message=(f"Preview: would scaffold repo '{plan.repo_name}' with {len(plan.files)} file(s) "
                     f"(README + architecture/ER diagrams, models, API stubs, Docker/CI/docs), "
                     f"{len(plan.milestones)} milestone(s) and {len(plan.issues)} issue(s). "
                     f"Paste your own GitHub PAT (repo scope) and create it for real — the "
                     f"repository is made in your account, not the operator's."),
        )

    from aps.infra import http
    headers = {"Authorization": f"Bearer {token}",
               "Accept": "application/vnd.github+json",
               "X-GitHub-Api-Version": "2022-11-28"}
    try:
        # 1) create the repository. auto_init gives an initial commit (the Git Data API 409s on an
        #    empty repo). If the name is already taken (422), retry with -2, -3… so a repeat launch
        #    never dead-ends — it just makes the next available name.
        base_name = plan.repo_name
        r = None
        for attempt in range(6):
            name = base_name if attempt == 0 else f"{base_name}-{attempt + 1}"
            r = http.post(f"{_GH}/user/repos", headers=headers,
                          json={"name": name, "description": plan.description,
                                "private": private, "auto_init": True})
            if r.status_code in (401, 403):
                # most common live failure: the PAT can't create repos. Say exactly how to fix it.
                return LaunchResult(
                    created=False, dry_run=False,
                    message=(f"GitHub denied repo creation (HTTP {r.status_code}: "
                             f"'{(r.json() or {}).get('message', 'forbidden')}'). This token can't "
                             "create repositories — use a CLASSIC PAT with the 'repo' scope, or a "
                             "fine-grained token with Administration: Read and write."))
            if r.status_code == 422:   # name taken (or invalid) → try the next suffix
                continue
            break
        if r is None or r.status_code == 422:
            return LaunchResult(created=False, dry_run=False,
                                message=f"GitHub rejected the repo (HTTP 422: "
                                        f"'{(r.json() or {}).get('message', 'unprocessable') if r else 'unprocessable'}'). "
                                        f"'{base_name}' and -2..-6 all appear to exist already — "
                                        "delete one or rename the venture.")
        r.raise_for_status()
        repo = r.json()
        full_name = repo["full_name"]
        repo_url = repo["html_url"]
        default_branch = repo.get("default_branch") or "main"

        # 2) push the full scaffold as ONE initial commit via the Git Data API: build a tree with
        #    every file's content inline (one call), create the root commit (no parent), point
        #    refs/heads/main at it. Far fewer calls than one-PUT-per-file, and atomic.
        files = plan.files or [("README.md", plan.readme)]
        files_created = 0
        try:
            # the repo has one auto-init commit; build the scaffold tree on top of it and advance
            # the branch. base_tree carries over the auto-init blob; our README.md overwrites it.
            head = http.request("GET", f"{_GH}/repos/{full_name}/git/ref/heads/{default_branch}", headers=headers)
            head.raise_for_status()
            head_sha = head.json()["object"]["sha"]
            base_tree = http.request("GET", f"{_GH}/repos/{full_name}/git/commits/{head_sha}",
                                     headers=headers).json()["tree"]["sha"]
            tree = [{"path": p, "mode": "100644", "type": "blob", "content": c} for p, c in files]
            tr = http.post(f"{_GH}/repos/{full_name}/git/trees", headers=headers,
                           json={"base_tree": base_tree, "tree": tree})
            tr.raise_for_status()
            cm = http.post(f"{_GH}/repos/{full_name}/git/commits", headers=headers,
                           json={"message": "Scaffold project (APS)", "tree": tr.json()["sha"],
                                 "parents": [head_sha]})
            cm.raise_for_status()
            http.request("PATCH", f"{_GH}/repos/{full_name}/git/refs/heads/{default_branch}",
                         headers=headers, json={"sha": cm.json()["sha"], "force": True}).raise_for_status()
            files_created = len(files)
        except Exception:
            # fallback: at least land the README via the Contents API so the repo isn't empty.
            http.request("PUT", f"{_GH}/repos/{full_name}/contents/README.md", headers=headers,
                         json={"message": "Initial README (APS)",
                               "content": base64.b64encode(plan.readme.encode()).decode()}).raise_for_status()
            files_created = 1

        # 3) milestones -> {title: number}
        ms_numbers: dict[str, int] = {}
        for title in plan.milestones:
            mr = http.post(f"{_GH}/repos/{full_name}/milestones", headers=headers,
                           json={"title": title})
            if mr.status_code < 300:
                ms_numbers[title] = mr.json().get("number")

        # 4) issues (attach milestone when the item belongs to a sprint)
        issue_urls: list[str] = []
        for iss in plan.issues:
            payload: dict = {"title": iss.title, "body": iss.body, "labels": iss.labels}
            if iss.sprint is not None and f"Sprint {iss.sprint}" in ms_numbers:
                payload["milestone"] = ms_numbers[f"Sprint {iss.sprint}"]
            ir = http.post(f"{_GH}/repos/{full_name}/issues", headers=headers, json=payload)
            if ir.status_code < 300:
                issue_urls.append(ir.json().get("html_url"))

        return LaunchResult(
            created=True, dry_run=False, repo_url=repo_url, full_name=full_name,
            issue_urls=issue_urls, milestones_created=len(ms_numbers), files_created=files_created,
            message=f"Created {full_name} with {files_created} file(s), {len(issue_urls)} issue(s) "
                    f"and {len(ms_numbers)} milestone(s).",
        )
    except Exception as e:
        return LaunchResult(created=False, dry_run=False,
                            message=f"GitHub launch failed: {type(e).__name__}: {str(e)[:200]}")
