"""Deterministic repo scaffold for GitHub Launch Mode.

Turns the artifacts APS has ALREADY generated (PRD, TRD, Execution plan) into a real starter
repository — README with rendered architecture + ER diagrams, models/routes derived from the
TRD data-model + OpenAPI spec, Docker/CI/config, and docs. Pure transformation: **no LLM and no
new API calls** (so it never re-burns research). Every file carries a header comment and `TODO:`
steps drawn from the backlog/features, so the repo reads like a proper scaffold, not an empty shell.

`build_scaffold(...)` returns `[(path, content)]`; the launcher commits them all in one tree.
"""
from __future__ import annotations

import json
from typing import Any

_GEN = "Generated by Autonomous Product Studio (APS) - fill in the TODOs to ship."

# data-model type → SQLAlchemy column type
_SA_TYPE = {
    "uuid": "UUID(as_uuid=True)", "string": "String(255)", "str": "String(255)", "text": "Text",
    "int": "Integer", "integer": "Integer", "bigint": "BigInteger", "float": "Float",
    "number": "Float", "decimal": "Float", "bool": "Boolean", "boolean": "Boolean",
    "datetime": "DateTime(timezone=True)", "timestamp": "DateTime(timezone=True)",
    "date": "Date", "json": "JSON", "jsonb": "JSON",
}


# --------------------------------------------------------------------------- #
# small helpers
# --------------------------------------------------------------------------- #
def _stack_str(trd) -> str:
    return " ".join(trd.stack).lower() if trd and getattr(trd, "stack", None) else ""


def _is_python(trd) -> bool:
    s = _stack_str(trd)
    return (not s) or any(k in s for k in ("fastapi", "python", "django", "flask"))


def _has_frontend(trd) -> bool:
    s = _stack_str(trd)
    return any(k in s for k in ("react", "next", "vue", "svelte", "typescript", "node", "frontend"))


def _db(trd) -> str:
    s = _stack_str(trd)
    for k in ("postgres", "mysql", "mongo", "sqlite", "redis"):
        if k in s:
            return "postgres" if k == "redis" else k
    return "postgres"


def _classname(name: str) -> str:
    parts = "".join(c if c.isalnum() else " " for c in (name or "Entity")).split()
    return "".join(p[:1].upper() + p[1:] for p in parts) or "Entity"


def _snake(name: str) -> str:
    out = "".join(("_" + c.lower()) if c.isupper() else c for c in (name or "")).strip("_")
    return "".join(c if c.isalnum() or c == "_" else "_" for c in out).strip("_").lower() or "item"


def _entities(trd) -> list[tuple[str, dict[str, str]]]:
    """Normalize TRD.data_model.entities (dict-of-dict or list-of-dict) → [(Name, {field: type})]."""
    dm = (getattr(trd, "data_model", None) or {}) if trd else {}
    ents = dm.get("entities") or {}
    out: list[tuple[str, dict[str, str]]] = []

    def _fields(spec: Any) -> dict[str, str]:
        f = (spec or {}).get("fields") if isinstance(spec, dict) else None
        f = f or {}
        if isinstance(f, list):
            return {d.get("name"): d.get("type", "string") for d in f if isinstance(d, dict) and d.get("name")}
        return {k: (v if isinstance(v, str) else "string") for k, v in f.items()} if isinstance(f, dict) else {}

    if isinstance(ents, dict):
        for name, spec in ents.items():
            out.append((str(name), _fields(spec)))
    elif isinstance(ents, list):
        for spec in ents:
            name = spec.get("name") if isinstance(spec, dict) else None
            if name:
                out.append((str(name), _fields(spec)))
    return out


def _paths(trd) -> dict:
    spec = (getattr(trd, "api_spec", None) or {}) if trd else {}
    return spec.get("paths") or {}


# --------------------------------------------------------------------------- #
# file generators
# --------------------------------------------------------------------------- #
def _arch_mermaid(trd) -> tuple[str, str]:
    try:
        from aps.render.architecture_mmd import _flowchart, _er
        dm = (getattr(trd, "data_model", None) or {}) if trd else {}
        return _flowchart(dm), _er(dm)
    except Exception:
        return "", ""


def _file_tree(paths: list[str]) -> str:
    """A simple indented tree from a flat list of file paths (for the README)."""
    tree: dict = {}
    for p in sorted(paths):
        node = tree
        for part in p.split("/"):
            node = node.setdefault(part, {})
    lines: list[str] = []

    def walk(node: dict, prefix: str) -> None:
        items = sorted(node.items())
        for i, (name, child) in enumerate(items):
            last = i == len(items) - 1
            lines.append(f"{prefix}{'└── ' if last else '├── '}{name}")
            if child:
                walk(child, prefix + ("    " if last else "│   "))
    walk(tree, "")
    return "```\n" + "\n".join(lines) + "\n```"


def _readme(idea: str, prd, trd, execution, file_paths: list[str]) -> str:
    flow, er = _arch_mermaid(trd)
    L: list[str] = []
    L.append(f"# {idea}\n")
    L.append("![status](https://img.shields.io/badge/status-scaffold-blue) "
             "![built with](https://img.shields.io/badge/built%20with-APS-7c3aed) "
             "![license](https://img.shields.io/badge/license-MIT-green)\n")
    L.append("> Generated by **Autonomous Product Studio** — idea → research → architecture → a runnable scaffold.\n")
    if prd and getattr(prd, "mvp_scope", ""):
        L.append("## Overview\n")
        L.append(prd.mvp_scope.strip() + "\n")
    if prd and getattr(prd, "features", None):
        L.append("## Features\n")
        for f in prd.features[:12]:
            L.append(f"- **{f.title}** `[{f.priority}]` — {f.description}")
        L.append("")
    if flow:
        L.append("## Architecture\n")
        L.append("```mermaid\n" + flow.strip() + "\n```\n")
    if er:
        L.append("## Data Model\n")
        L.append("```mermaid\n" + er.strip() + "\n```\n")
    if trd and getattr(trd, "stack", None):
        L.append("## Tech Stack\n")
        for s in trd.stack:
            L.append(f"- {s}")
        L.append("")
    L.append("## Project Structure\n")
    L.append(_file_tree(file_paths) + "\n")
    L.append("## Quick Start\n")
    if _is_python(trd):
        L.append("```bash")
        L.append("# 1) backend")
        L.append("cd backend && python -m venv .venv && source .venv/bin/activate")
        L.append("pip install -r requirements.txt")
        L.append("uvicorn app.main:app --reload      # → http://localhost:8000/docs")
        L.append("```")
    L.append("\nOr run the whole stack with Docker:\n")
    L.append("```bash\ndocker compose -f infra/docker-compose.yml up --build\n```\n")
    L.append("## Roadmap\n")
    L.append("See [`docs/ROADMAP.md`](docs/ROADMAP.md). Architecture details in "
             "[`docs/ARCHITECTURE.md`](docs/ARCHITECTURE.md); API in [`docs/API.md`](docs/API.md).\n")
    L.append("---\n*Scaffolded by APS. Each file has `TODO:` markers — implement them to ship.*\n")
    return "\n".join(L)


def _architecture_md(idea: str, trd) -> str:
    flow, er = _arch_mermaid(trd)
    L = [f"# Architecture — {idea}\n", _gen_note(), ""]
    L.append("## System Architecture\n")
    L.append("```mermaid\n" + (flow.strip() or "flowchart TD\n    Client --> API --> DB") + "\n```\n")
    L.append("## Data Model (ER)\n")
    L.append("```mermaid\n" + (er.strip() or "erDiagram") + "\n```\n")
    if trd and getattr(trd, "scale_estimate", ""):
        L.append("## Scale & Non-Functional\n")
        L.append(trd.scale_estimate.strip() + "\n")
    return "\n".join(L)


def _api_md(trd) -> str:
    paths = _paths(trd)
    L = ["# API Reference\n", _gen_note(), "", "Derived from `docs/openapi.json`.\n", "| Method | Path | Summary |", "|---|---|---|"]
    for path, methods in paths.items():
        for method, op in (methods or {}).items():
            if method.lower() not in ("get", "post", "put", "patch", "delete"):
                continue
            summary = (op or {}).get("summary") or (op or {}).get("operationId") or ""
            L.append(f"| `{method.upper()}` | `{path}` | {summary} |")
    if len(L) == 6:
        L.append("| `GET` | `/health` | Liveness probe |")
    return "\n".join(L) + "\n"


def _roadmap_md(execution) -> str:
    L = ["# Roadmap\n", _gen_note(), ""]
    if execution and getattr(execution, "roadmap", ""):
        L.append(execution.roadmap.strip() + "\n")
    for s in (getattr(execution, "sprints", None) or []):
        L.append(f"## Sprint {s.get('sprint', '?')}\n")
        for it in s.get("items", []):
            L.append(f"- [ ] {it.get('title', 'task')}  `{it.get('priority', '')}`")
        L.append("")
    return "\n".join(L)


def _models_py(trd) -> str:
    ents = _entities(trd)
    head = [
        '"""Database models — generated from the APS Technical Design data model.',
        "",
        _GEN,
        '"""',
        "from __future__ import annotations",
        "",
        "import uuid",
        "",
        "from sqlalchemy import (Column, String, Integer, BigInteger, Float, Boolean,",
        "                        DateTime, Date, Text, JSON, ForeignKey)  # noqa: F401",
        "from sqlalchemy.dialects.postgresql import UUID",
        "from sqlalchemy.orm import declarative_base",
        "",
        "Base = declarative_base()",
        "",
        "",
    ]
    body: list[str] = []
    if not ents:
        body += ["# TODO: the data model had no entities — define your tables here.", ""]
    for name, fields in ents:
        cls = _classname(name)
        body.append(f"class {cls}(Base):")
        body.append(f'    """{name}."""')
        body.append(f'    __tablename__ = "{_snake(name)}s"')
        if "id" not in fields:
            body.append("    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)")
        for fname, ftype in fields.items():
            sa = _SA_TYPE.get((ftype or "string").strip().lower(), "String(255)")
            args = [sa]
            if fname == "id":
                args.append("primary_key=True")
                if "uuid" in sa.lower():
                    args.append("default=uuid.uuid4")
            note = "  # TODO: foreign key — point to the referenced table" if fname.endswith("_id") and fname != "id" else ""
            body.append(f"    {fname} = Column({', '.join(args)}){note}")
        body += ["", ""]
    return "\n".join(head + body)


def _routes_py(trd) -> str:
    paths = _paths(trd)
    head = [
        '"""API routes — generated from the APS OpenAPI design (docs/openapi.json).',
        "",
        "Each endpoint's method + path + params are real; the body is a TODO stub.",
        _GEN,
        '"""',
        "from __future__ import annotations",
        "",
        "from fastapi import APIRouter, HTTPException",
        "",
        'router = APIRouter()',
        "",
        "",
    ]
    body: list[str] = []
    seen: set[str] = set()
    for path, methods in paths.items():
        for method, op in (methods or {}).items():
            m = method.lower()
            if m not in ("get", "post", "put", "patch", "delete"):
                continue
            summary = (op or {}).get("summary") or (op or {}).get("operationId") or f"{m.upper()} {path}"
            params = [seg[1:-1] for seg in path.split("/") if seg.startswith("{") and seg.endswith("}")]
            fn = (m + "_" + "_".join(p for p in path.strip("/").split("/") if not p.startswith("{"))).strip("_") or f"{m}_root"
            while fn in seen:
                fn += "_x"
            seen.add(fn)
            sig = ", ".join(f"{p}: str" for p in params)
            body.append(f'@router.{m}("{path}")')
            body.append(f"def {fn}({sig}):")
            body.append(f'    """{summary}."""')
            body.append(f"    # TODO: implement {m.upper()} {path}")
            body.append('    raise HTTPException(status_code=501, detail="Not implemented yet")')
            body.append("")
    if not body:
        body = ['@router.get("/health")', "def health():", '    """Liveness probe."""',
                '    return {"status": "ok"}', ""]
    return "\n".join(head + body)


def _main_py(idea: str) -> str:
    return (
        f'"""FastAPI application entry point for {idea}.\n\n{_GEN}\n"""\n'
        "from fastapi import FastAPI\n\n"
        "from app.api.routes import router\n\n"
        f'app = FastAPI(title="{idea}", version="0.1.0")\n'
        "app.include_router(router)\n\n\n"
        '@app.get("/")\n'
        "def root():\n"
        f'    return {{"app": "{idea}", "status": "scaffolded by APS"}}\n'
    )


def _config_py(idea: str, db: str) -> str:
    dsn = {"postgres": "postgresql+psycopg://app:app@localhost:5432/app",
           "mysql": "mysql+pymysql://app:app@localhost:3306/app",
           "sqlite": "sqlite:///./app.db", "mongo": "mongodb://localhost:27017/app"}.get(db, "sqlite:///./app.db")
    return (
        f'"""App configuration. {_GEN}"""\n'
        "import os\n\n\n"
        "class Settings:\n"
        f'    app_name: str = "{idea}"\n'
        f'    database_url: str = os.getenv("DATABASE_URL", "{dsn}")\n'
        '    debug: bool = os.getenv("DEBUG", "true").lower() == "true"\n\n\n'
        "settings = Settings()\n"
    )


def _requirements(db: str) -> str:
    reqs = ["fastapi>=0.111", "uvicorn[standard]>=0.30", "pydantic>=2.7", "SQLAlchemy>=2.0"]
    if db == "postgres":
        reqs.append("psycopg[binary]>=3.1")
    elif db == "mysql":
        reqs.append("PyMySQL>=1.1")
    reqs.append("python-dotenv>=1.0")
    return "# " + _GEN + "\n" + "\n".join(reqs) + "\n"


def _dockerfile() -> str:
    return (
        "# " + _GEN + "\n"
        "FROM python:3.11-slim\n"
        "WORKDIR /app\n"
        "COPY requirements.txt .\n"
        "RUN pip install --no-cache-dir -r requirements.txt\n"
        "COPY . .\n"
        'CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]\n'
    )


def _compose(idea: str, db: str) -> str:
    svc = {
        "postgres": "  db:\n    image: postgres:16\n    environment:\n      POSTGRES_USER: app\n      POSTGRES_PASSWORD: app\n      POSTGRES_DB: app\n    ports: [\"5432:5432\"]\n",
        "mysql": "  db:\n    image: mysql:8\n    environment:\n      MYSQL_ROOT_PASSWORD: app\n      MYSQL_DATABASE: app\n    ports: [\"3306:3306\"]\n",
        "mongo": "  db:\n    image: mongo:7\n    ports: [\"27017:27017\"]\n",
        "sqlite": "",
    }.get(db, "")
    return (
        "# " + _GEN + "\n"
        "services:\n"
        "  api:\n"
        "    build: ../backend\n"
        '    ports: ["8000:8000"]\n'
        + ("    depends_on: [db]\n" if svc else "")
        + svc
    )


def _ci() -> str:
    return (
        "# " + _GEN + "\n"
        "name: CI\n"
        "on: [push, pull_request]\n"
        "jobs:\n"
        "  build:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - uses: actions/setup-python@v5\n"
        '        with: { python-version: "3.11" }\n'
        "      - run: pip install -r backend/requirements.txt\n"
        "      - run: pip install pytest && pytest backend -q || true   # TODO: drop the || true once tests exist\n"
    )


def _test_smoke(idea: str) -> str:
    return (
        f'"""Smoke test. {_GEN}"""\n'
        "from fastapi.testclient import TestClient\n\n"
        "from app.main import app\n\n"
        "client = TestClient(app)\n\n\n"
        "def test_root():\n"
        '    assert client.get("/").status_code == 200\n'
    )


def _gitignore() -> str:
    return ("# " + _GEN + "\n__pycache__/\n*.py[cod]\n.venv/\nvenv/\n.env\n*.db\n"
            "node_modules/\ndist/\nbuild/\n.DS_Store\n.coverage\n.pytest_cache/\n")


def _env_example(db: str) -> str:
    dsn = {"postgres": "postgresql+psycopg://app:app@localhost:5432/app",
           "mysql": "mysql+pymysql://app:app@localhost:3306/app",
           "sqlite": "sqlite:///./app.db", "mongo": "mongodb://localhost:27017/app"}.get(db, "sqlite:///./app.db")
    return f"# {_GEN}\nDATABASE_URL={dsn}\nDEBUG=true\n"


def _contributing(idea: str) -> str:
    return (
        f"# Contributing to {idea}\n\n{_gen_note()}\n\n"
        "1. Fork & branch from `main`.\n"
        "2. Implement a `TODO:` (start with the open issues — each maps to a backlog item).\n"
        "3. `pip install -r backend/requirements.txt && pytest backend`.\n"
        "4. Open a PR referencing the issue.\n"
    )


def _license() -> str:
    return (
        "MIT License\n\n"
        "Copyright (c) 2026\n\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy "
        'of this software and associated documentation files (the "Software"), to deal '
        "in the Software without restriction...\n\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND.\n"
    )


def _package_json(idea: str) -> str:
    return json.dumps({
        "name": _snake(idea).replace("_", "-"),
        "version": "0.1.0",
        "private": True,
        "description": f"{idea} — frontend (scaffolded by APS)",
        "scripts": {"dev": "vite", "build": "vite build", "preview": "vite preview"},
        "dependencies": {"react": "^18.2.0", "react-dom": "^18.2.0"},
        "devDependencies": {"vite": "^5.0.0", "typescript": "^5.4.0"},
    }, indent=2) + "\n"


def _gen_note() -> str:
    return f"> {_GEN}"


# --------------------------------------------------------------------------- #
# entry point
# --------------------------------------------------------------------------- #
def build_scaffold(idea: str, prd, trd, execution, pitch) -> list[tuple[str, str]]:
    """Build the full file list for the repo (paths relative to the repo root)."""
    db = _db(trd)
    files: list[tuple[str, str]] = []

    # docs + top-level (computed first so the README can show the real tree)
    docs: list[tuple[str, str]] = [
        ("docs/ARCHITECTURE.md", _architecture_md(idea, trd)),
        ("docs/ROADMAP.md", _roadmap_md(execution)),
        ("CONTRIBUTING.md", _contributing(idea)),
        ("LICENSE", _license()),
        (".gitignore", _gitignore()),
        (".env.example", _env_example(db)),
        (".github/workflows/ci.yml", _ci()),
    ]
    if trd and getattr(trd, "api_spec", None):
        docs.append(("docs/API.md", _api_md(trd)))
        docs.append(("docs/openapi.json", json.dumps(trd.api_spec, indent=2) + "\n"))

    backend: list[tuple[str, str]] = []
    if _is_python(trd):
        backend = [
            ("backend/app/__init__.py", ""),
            ("backend/app/main.py", _main_py(idea)),
            ("backend/app/config.py", _config_py(idea, db)),
            ("backend/app/api/__init__.py", ""),
            ("backend/app/api/routes.py", _routes_py(trd)),
            ("backend/app/models/__init__.py", ""),
            ("backend/app/models/schema.py", _models_py(trd)),
            ("backend/requirements.txt", _requirements(db)),
            ("backend/Dockerfile", _dockerfile()),
            ("backend/tests/test_smoke.py", _test_smoke(idea)),
        ]

    frontend: list[tuple[str, str]] = []
    if _has_frontend(trd):
        frontend = [
            ("frontend/package.json", _package_json(idea)),
            ("frontend/README.md", f"# {idea} — Frontend\n\n{_gen_note()}\n\n`npm install && npm run dev`\n"),
        ]

    infra = [("infra/docker-compose.yml", _compose(idea, db))]

    body_files = docs + backend + frontend + infra
    all_paths = [p for p, _ in body_files] + ["README.md"]
    readme = _readme(idea, prd, trd, execution, all_paths)

    files = [("README.md", readme)] + body_files
    return files
